config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  root to: 'home#index'

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }

  # landing page
  get 'featured_games', to: 'home#featured_games';

  get 'categories', to: 'categories#index', as: 'categories'
  get 'categories/sort', to: 'categories#sort'

  get 'games/new', to: 'games#new', as: 'new_game'
  get 'games/:id', to: 'games#show', as: 'game'
  get 'games/:id/edit', to: 'games#edit', as: 'edit_game'
  post 'games/new', to: 'games#create', as: 'create_game'
  put 'games/:id', to: 'games#update'
  delete 'games/:id', to: 'games#destroy'
  delete 'games/:id/user/:user_id', to: 'games#remove_games_users', as: 'remove_games_users'

  get 'users/:id', to: 'users#show_profile'
  get 'users/:id/edit', to: 'users#edit'
  put 'profile', to: 'users#update', as: 'update_profile'
  get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
  get 'profile', to: 'users#show_profile', as: 'profile'

  get 'rooms/:id', to: 'rooms#show'

  post 'messages', to: 'messages#create'

  post 'requests', to: 'requests#create'
  put 'requests', to: 'requests#update', as: 'edit_request'
  delete 'requests/:id', to: 'requests#destroy', as: 'destroy_request'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  include Gravtastic
  gravtastic :default => 'https://www.xeus.com/wp-content/uploads/2014/09/One_User_Orange.png'
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_and_belongs_to_many :games
  has_many :requests

  #Active Storage
  has_one_attached :avatar

  after_commit :update_user_name, on: :create

  def update_user_name
    user = User.last
    user.update(name: user.email.to_s.split('@')[0])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user
  helper_method :group_by_day

  def show_dashboard


    @participating_games = group_by_day(current_user.games)
    @hosting_games = group_by_day(Game.where(host_id: current_user.id))
    #Edit links here for navbar
    @links = [{:name => "Home", :path => root_path}, {:name => "Host a Game", :path => new_game_path}, {:name => "Join a Game", :path => categories_path}]

  end

  def show_profile
    @user = current_user
    @links = [{:name => "Host a Game", :path => new_game_path}, {:name => "Join a Game", :path => categories_path}, {:name => "Dashboard", :path => dashboard_path}]
  end

  def edit
  end

  def update
    @user = current_user
    redirect_to profile_path if current_user.update(user_params)
  end

  private
    def check_user
      if !current_user
        redirect_to root_path
      end
    end

    def user_params
      params.require(:user).permit(:name, :avatar)
    end

    def group_by_day(obj) 
      sort_by_day = -> ( d ) {d.start.strftime("%A, %b %d %y")}
      return obj.group_by(&sort_by_day)
    end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show_dashboard.html.erb
<div class="wrapper">
		<div class="section">
				<h1 class="section-title">Currently Hosting</h1>
				<% if @hosting_games.empty? %>
				<div class="section text-center">
						<h1 class="font-bold font-lg">You are not hosting any games at the moment.</h1>
						<%= link_to  "Host a new game now? ", main_app.new_game_path, class: "font-bold font-lg" %>
				</div>
				<% end %>
				<% @hosting_games.each do |date, games| %>
				<% if games.count %>
				<h2 class="section-subtitle">
						<%= date %>, <span class="text-gray-700">
								<%= distance_of_time_in_words(Time.now, games[0].start) %>&nbsp;later</span>
				</h2>
				<div class="gallery justify-start">
						<% games.each do |game| %>
						<div class="card gallery-item gallery-item_short gallery-item_wide gallery-item_left_aligned">
								<div class="card-header">
										<h1 class="card-subtitle text-right">
												<%= game.category.game_type %>
										</h1>
										<h2 class="card-title">
												<%= game.title %>
										</h2>
								</div>
								<div class="card-body ml-0">
										<p><i class="fas fa-calendar-star text-black icon"></i>
												<%= game.start.strftime("%H:%M %P") if game.start %> -
												<%=game.end.strftime("%H:%M %P") if game.end %>
										</p>
								</div>
								<div class="card-body ml-0">
										<p> <i class="fas fa-compass text-black icon"></i>
												<%= game.venue%>
										</p>
								</div>
								<div class="card-footer flex justify-between items-center">
										<%= button_to "Details", game_path(game.id),  class:'btn btn-default btn-sm', method:'get' %>
										<div>
												<a href="" class="text-xs">
														<%= game.pending_requests.count %>&nbsp;pending requests</a> <!-- link to details -->
												<p>
														<%= game.users.count %>/
														<%= pluralize( game.players_required, 'member' ) %>
												</p>
										</div>
								</div>
						</div>
						<% end %>
				</div>
				<% end %>
				<% end %>
		</div>
		<!--end section -->
		<section>
				<h1 class="section-title">Participating</h1>
				<% if @participating_games.empty? %>
				<div class="section text-center">
						<h1 class="font-bold font-lg">You are not participating in any games yet</h1>
						<%= link_to  "Join a game?", main_app.categories_path, class:'font-bold font-md' %>
				</div>
				<% end %>
				<% @participating_games.each do |date, games| %>
				<% if games.count %>
				<h2 class="section-subtitle">
						<%= date %>, <span class="text-gray-700">
								<%= distance_of_time_in_words(Time.now, games[0].start) %>&nbsp;later</span>
				</h2>
				<div class="gallery justify-start">
						<% games.each do |game| %>
						<div class="card gallery-item gallery-item_short gallery-item_wide gallery-item_left_aligned">
								<div class="card-header">
										<% if User.find(game.host_id).avatar.attached?%>
										<%= image_tag main_app.url_for(User.find(game.host_id).avatar), class: "card-img object-cover" %>
										<%else%>
										<%= image_tag User.find(game.host_id).gravatar_url, class: "card-img object-cover" %>
										<%end%>
										<h1 class="card-subtitle text-left">
												<%= game.category.game_type %>
										</h1>
										<h2 class="card-title">
												<%= game.title %>
										</h2>
								</div>
								<div class="card-body ml-0">
										<p><i class="fas fa-calendar-star text-black icon"></i>
												<%= game.start.strftime("%H:%M %P") if game.start %> -
												<%=game.end.strftime("%H:%M %P") if game.end %>
										</p>
								</div>
								<div class="card-body ml-0">
										<p> <i class="fas fa-compass text-black icon"></i>
												<%= game.venue%>
										</p>
								</div>
								<div class="card-footer flex justify-between items-center">
										<%= button_to "Details", game_path(game.id),  class:'btn btn-default btn-sm', method:'get' %>
										<div>
												<p>
														<%= game.users.count %>/
														<%= pluralize( game.players_required, 'member' ) %>
												</p>
										</div>
								</div>
						</div>
						<% end %>
				</div>
				<% end %>
				<% end %>
		</section>
</div>

app/views/users/show_profile.html.erb
<div class="profile__container flex flex-col justify-center items-center">
		<%= form_with(model: @user, url: update_profile_path, local: true, method: "put", class: "flex flex-col justify-around items-center ") do |form| %>
		<% if current_user.avatar.attached? %>
		<%= image_tag current_user.avatar, class: "gravatar__profile mb-4" %>
		<%else%>
		<%= image_tag current_user.gravatar_url, class: "gravatar__profile mb-4" if user_signed_in?%>
		<%end%>
		<div class="avatar__field mt-2 mb-4 hidden flex flex-col justify-around items-center">
				<%= form.label :avatar, "Upload Avatar", class: "avatar__file-label "%>
				<%= form.file_field :avatar, value: @user.avatar, class: "avatar__file-input" %>
				<div class="avatar__input-display hidden w-11/12 text-sm p-1 text-gray-600 text-center"></div>
		</div>
		<div class="name__field mt-1 mb-4 w-full">
				<%= form.label :name, class: "hidden name__field-label" %><br>
				<%= form.text_field :name, value: @user.name, class: "name__field border-0 shadow-none outline-none text-center p-1 text-xl uppercase w-full tracking-widest" %>
		</div>
		<div class="profile__btn-container mt-12">
				<%= form.submit 'Update Profile', class: "profile__update-btn hidden btn-default btn" %>
				<button class="profile__edit-btn btn-default btn" type="button">Edit Profile</button>
		</div>
		<%end%>
</div>