config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  root to: 'home#index'

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }

  # landing page
  get 'featured_games', to: 'home#featured_games';

  get 'categories', to: 'categories#index', as: 'categories'
  get 'categories/sort', to: 'categories#sort'

  get 'games/new', to: 'games#new', as: 'new_game'
  get 'games/:id', to: 'games#show', as: 'game'
  get 'games/:id/edit', to: 'games#edit', as: 'edit_game'
  post 'games/new', to: 'games#create', as: 'create_game'
  put 'games/:id', to: 'games#update'
  delete 'games/:id', to: 'games#destroy'
  delete 'games/:id/user/:user_id', to: 'games#remove_games_users', as: 'remove_games_users'

  get 'users/:id', to: 'users#show_profile'
  get 'users/:id/edit', to: 'users#edit'
  put 'profile', to: 'users#update', as: 'update_profile'
  get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
  get 'profile', to: 'users#show_profile', as: 'profile'

  get 'rooms/:id', to: 'rooms#show'

  post 'messages', to: 'messages#create'

  post 'requests', to: 'requests#create'
  put 'requests', to: 'requests#update', as: 'edit_request'
  delete 'requests/:id', to: 'requests#destroy', as: 'destroy_request'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :game

  after_commit :create_join_request_notifications, on: :create
  after_commit :withdraw_join_request_notifications, on: :destroy
  after_commit :update_join_request_notifications, on: :update

  private

  def create_join_request_notifications
    Notification.create do |notification|
      notification.notify_type = 'join_request'
      notification.actor = self.user
      notification.user = User.find(self.game.host_id)
      notification.target = self
      notification.second_target = self.game
    end

    notification = Notification.last
    notifications = Notification.unread_count(User.find(self.game.host_id))

    ActionCable.server.broadcast "activity_channel", notification: "You received a notification", notification_actor_id: notification.actor.id, notification_actor_email: notification.actor.email, notification_user_id: notification.user.id,notification_user_email: notification.user.email,notification_subject: notification.second_target.title, total_notifications: notifications
  end

  def withdraw_join_request_notifications
    Notification.create do |notification|
      notification.notify_type = 'withdraw_request'
      notification.actor = self.user
      notification.user = User.find(self.game.host_id)
      notification.target = self
      notification.second_target = self.game
    end

    notification = Notification.last
    notifications = Notification.unread_count(User.find(self.game.host_id))

    ActionCable.server.broadcast "activity_channel", notification: "You received a notification", notification_actor_id: notification.actor.id, notification_actor_email: notification.actor.email, notification_user_id: notification.user.id,notification_user_email: notification.user.email,notification_subject: notification.second_target.title, total_notifications: notifications
  end

  def update_join_request_notifications
    if self.status == 0
      Notification.create do |notification|
        notification.notify_type = 'left_game'
        notification.actor = self.user
        notification.user = User.find(self.game.host_id)
        notification.target = self
        notification.second_target = self.game
      end

      notification = Notification.last
      notifications = Notification.unread_count(User.find(self.game.host_id))

      ActionCable.server.broadcast "activity_channel", notification: "You received a notification", notification_actor_id: notification.actor.id, notification_actor_email: notification.actor.email, notification_user_id: notification.user.id,notification_user_email: notification.user.email,notification_subject: notification.second_target.title, total_notifications: notifications

    elsif self.status == -1
      Notification.create do |notification|
        notification.notify_type = 'kick_user'
        notification.actor = User.find(self.game.host_id)
        notification.user = self.user
        notification.target = self
        notification.second_target = self.game
      end

      notification = Notification.last
      notifications = Notification.unread_count(self.user)

      ActionCable.server.broadcast "activity_channel", notification: "You received a notification", notification_actor_id: notification.actor.id, notification_actor_email: notification.actor.email, notification_user_id: notification.user.id,notification_user_email: notification.user.email,notification_subject: notification.second_target.title, total_notifications: notifications

    else
      Notification.create do |notification|
        notification.notify_type = 'update_request'
        notification.actor = User.find(self.game.host_id)
        notification.user = self.user
        notification.target = self
        notification.second_target = self.game
      end

      notification = Notification.last
      notifications = Notification.unread_count(self.user)

      ActionCable.server.broadcast "activity_channel", notification: "You received a notification", notification_actor_id: notification.actor.id, notification_actor_email: notification.actor.email, notification_user_id: notification.user.id,notification_user_email: notification.user.email,notification_subject: notification.second_target.title, total_notifications: notifications
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:destroy]
  before_action :authenticate_user!

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)

    if Request.where(user_id: @request.user_id, game_id: @request.game_id, status: 3)[0]
      redirect_to game_path(@request.game)
    elsif @request.save
      game = Game.find(request_params[:game_id])
      redirect_to game_path(game)
    end
  end

  def update
    @request = Request.find(request_params[:id])

    if request_params[:status] == '1' && @request.game.requests.where(status: 1).count >= @request.game.players_required
      redirect_to game_path(@request.game)
    end

    if @request.update(request_params)
      game = Game.find(request_params[:game_id])
      if @request.status == 1
        user = User.find(request_params[:user_id])
        user.games.push(game)
      end
      redirect_to game_path(game)
    end

    # if request_params.status == 2
    #   Game.
    # end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy

    if @request.status == 1
      redirect_to game_path(@request.game_id)
    elsif @request.destroy
      redirect_to game_path(@request.game_id)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:user_id, :game_id, :status, :id)
    end
    
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<div class="join-game__btn-container w-full flex justify-center py-4">
		<%= form_with(model: request, remote: true) do |form| %>
		<% if request.errors.any? %>
		<div id="error_explanation">
				<h2>
						<%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>
				<ul>
						<% request.errors.full_messages.each do |message| %>
						<li>
								<%= message %>
						</li>
						<% end %>
				</ul>
		</div>
		<% end %>
		<%= form.hidden_field :user_id, value: current_user.id %>
		<%= form.hidden_field :game_id, value: @game.id %>
		<%= form.hidden_field :status, value: 3 %>
		<div class="actions">
				<%= form.submit "Join Game!", class: "btn btn-default"%>
		</div>
		<% end %>
</div>

app/views/requests/_host_request.html.erb
<div class="request-approve-reject__btns flex justify-around items-center w-full">
		<%= form_with(model: request, url: edit_request_path, method: "put", remote: true) do |form| %>
		<% if request.errors.any? %>
		<div id="error_explanation">
				<h2>
						<%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>
				<ul>
						<% request.errors.full_messages.each do |message| %>
						<li>
								<%= message %>
						</li>
						<% end %>
				</ul>
		</div>
		<% end %>
		<%= form.hidden_field :id, value: request.id%>
		<%= form.hidden_field :status, value: 1%>
		<%= form.hidden_field :user_id, value: request.user_id%>
		<%= form.hidden_field :game_id, value: game.id%>
		<div class="request-approve__btn-container">
				<%= form.submit "Approve!", class: "btn btn-default btn-sm mr-2 text-sm tracking-wider"%>
		</div>
		<% end %>
		<%= form_with(model: request, url: edit_request_path, method: "put", remote: true) do |form| %>
		<% if request.errors.any? %>
		<div id="error_explanation">
				<h2>
						<%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>
				<ul>
						<% request.errors.full_messages.each do |message| %>
						<li>
								<%= message %>
						</li>
						<% end %>
				</ul>
		</div>
		<% end %>
		<%= form.hidden_field :id, value: request.id%>
		<%= form.hidden_field :status, value: 2%>
		<%= form.hidden_field :user_id, value: request.user_id%>
		<%= form.hidden_field :game_id, value: game.id%>
		<div class="request-reject__btn-container">
				<%= form.submit "Reject!", class: "btn btn-default btn-sm ml-2 text-sm tracking-wider"%>
		</div>
		<% end %>
</div>