config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  root to: 'home#index'

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }

  # landing page
  get 'featured_games', to: 'home#featured_games';

  get 'categories', to: 'categories#index', as: 'categories'
  get 'categories/sort', to: 'categories#sort'

  get 'games/new', to: 'games#new', as: 'new_game'
  get 'games/:id', to: 'games#show', as: 'game'
  get 'games/:id/edit', to: 'games#edit', as: 'edit_game'
  post 'games/new', to: 'games#create', as: 'create_game'
  put 'games/:id', to: 'games#update'
  delete 'games/:id', to: 'games#destroy'
  delete 'games/:id/user/:user_id', to: 'games#remove_games_users', as: 'remove_games_users'

  get 'users/:id', to: 'users#show_profile'
  get 'users/:id/edit', to: 'users#edit'
  put 'profile', to: 'users#update', as: 'update_profile'
  get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
  get 'profile', to: 'users#show_profile', as: 'profile'

  get 'rooms/:id', to: 'rooms#show'

  post 'messages', to: 'messages#create'

  post 'requests', to: 'requests#create'
  put 'requests', to: 'requests#update', as: 'edit_request'
  delete 'requests/:id', to: 'requests#destroy', as: 'destroy_request'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  has_and_belongs_to_many :users
  belongs_to :category
  has_one :room, dependent: :destroy

  validates :title, :venue, :players_required, :start, :end, presence: true

  has_many :requests

  def pending_requests
    return requests.where(status: 3)
  end

  def participants
    return self.users.where.not(id: self.host_id)
  end
  
  def host
    return User.where(id: self.host_id)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, except: [:new, :create]
  before_action :authenticate_user!

  def show

    #Check if game is full (by checking accepted requests)
    @game_open = @game.requests.where(status: 1).count < @game.players_required

    #Select only pending requests
    @host_requests = @game.requests.select { |request| request.status == 3}
    @rejected_request = current_user.requests.find {|request| request.status == 2 && request.game_id == @game.id}
    @pending_request = current_user.requests.find {|request| request.status == 3 && request.game_id == @game.id}
    @accepted_request = current_user.requests.find {|request| request.status == 1 && request.game_id == @game.id}
    @user_in_game = @game.users.find {|user| user.id == current_user.id}
    # @request_made = current_user.requests.find {|request| request.game_id == @game.id}
    @room = Room.where(game_id: @game.id)[0]

    @game_participants = @game.requests.where(status: 1).count
    @spare_participants = @game_participants < @game.players_required
    #Edit links here for navbar
    @links = [{:name => "Home", :path => root_path}, {:name => "Host a Game", :path => new_game_path}, {:name => "Join a Game", :path => categories_path}, {:name => "Dashboard", :path => dashboard_path}]
  end

  def new
    @categories = Category.all
    #Edit links here for navbar
    @links = [{:name => "Home", :path => root_path},{:name => "Join a Game", :path => categories_path}, {:name => "Dashboard", :path => dashboard_path}]

    @game_params = {"title" => "", "location" => "", "players_required" => "", "special_requirements" => "", "cost" => "", "date" => "", "start_time" => "", "end_time" => ""}
  end

  def create
    # Manipulating date time input to fit model
    @date = game_params[:date]
    @start_time = game_params[:start_time]
    @end_time = game_params[:end_time]

    if @date == ""
      @start = ""
    elsif @start_time == ""
      @start = ""
      @end = @end_time
    elsif @end_time == ""
      @end = ""
      @start = @start_time
    else
      @start = DateTime.parse(@date + ' ' + @start_time)
      @end = DateTime.parse(@date + ' ' + @end_time)
    end

    @input_params = {"title" => game_params[:title], "venue" => game_params[:location], "players_required" => game_params[:players_required], "special_requirements" => game_params[:special_requirements], "start" => @start, "end" => @end, "category_id" => game_params[:category_id], "cost" => game_params[:cost], "host_id" => game_params[:host_id]}

    # Need to add host ID into the params

    # Insert into database
    @game = Game.new(@input_params)

    if @game.valid?
      @game.save

      @newgame = Game.last
      Room.create(game_id: @newgame.id)

      redirect_to dashboard_path
    else
      @categories = Category.all
      @links = [{:name => "Home", :path => root_path},{:name => "Join a Game", :path => categories_path}, {:name => "Dashboard", :path => dashboard_path}]
      @game_params = game_params
      render 'new'
    end

  end

  def edit
    @categories = Category.all
    @links = true
  end

  def update
    # Manipulating date time input to fit model
    @date = game_params[:date]
    @start_time = game_params[:start_time]
    @end_time = game_params[:end_time]

    @start = DateTime.parse(@date + ' ' + @start_time + "+08:00")
    @end = DateTime.parse(@date + ' ' + @end_time + "+08:00")
    @input_params = {"title" => game_params[:title], "venue" => game_params[:location], "players_required" => game_params[:players_required], "special_requirements" => game_params[:special_requirements], "start" => @start, "end" => @end, "category_id" => game_params[:category_id], "cost" => game_params[:cost], "host_id" => game_params[:host_id]}

    @game.update(@input_params)

    redirect_to game_path(@game)
  end

  def destroy
    @game.destroy
    redirect_to dashboard_path
  end

  def remove_games_users

    if current_user != User.find(@game.host_id)
      @game.users.delete(User.find(params[:user_id]))
      if User.find(params[:user_id]).requests.where(game_id: @game.id, status: 1)[0]
        if User.find(params[:user_id]).requests.where(game_id: @game.id, status: 1)[0].update(status: 0)
          redirect_to game_path(@game)
        end
      end
    else
      @game.users.delete(User.find(params[:user_id]))
      if User.find(params[:user_id]).requests.where(game_id: @game.id, status: 1)[0]
        if User.find(params[:user_id]).requests.where(game_id: @game.id, status: 1)[0].update(status: -1)
          redirect_to game_path(@game)
        end
      end
    end
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:category_id, :title, :date, :start_time, :end_time, :location, :players_required, :special_requirements, :cost, :host_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/edit.html.erb
<div class="wrapper">

  <section class="section">


    <%= form_with(model: @game, local: true, method: "put", class: "container mx-auto w-full md:w-4/5 lg:w-3/5 pb-16") do |form| %>


    <% categories_array = @categories.all.map { |category| [category.game_type, category.id] } %>
    <%= select(:game, :category_id, options_for_select(categories_array),{}, {class: "shadow shadow-none w-full h-8 my-3 mx-auto bg-white border-0 border-b border-black text-gray-600 md:mb-6  xl:mb-10"})%>

    <div class="block mb-4  md:mb-6 xl:mb-10">
      <%= form.label :title, class: 'text-gray-600' %><br>
      <%= form.text_field :title, class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
    </div>

    <div class="mb-4 md:mb-6 xl:mb-10">
      <h4 class="current-start-time">
        Date:
        <%= @game.start.to_s.split(" ")[0]%>
      </h4>
      <%= form.label :date, class: 'text-gray-600' %><br>
      <%= form.text_field :date, class: 'shadow shadow-none w-full date-flatpick h-8 bg-white border-0 border-b border-black' %>
    </div>


    <div class="inline-block mb-4 w-5/12 md:mb-6 xl:mb-10">
      <h4 class="current-start-time">
        Start Time:
        <%=@game.start.strftime("%I:%M %p")%>
      </h4>
      <%= form.label :start_time, "Pick new start time",class: 'text-gray-600' %><br>
      <%= form.text_field :start_time, class: 'shadow shadow-none w-full h-8 bg-white border-0 border-b border-black timestart-flatpick' %>
    </div>

    <div class="inline-block mb-4 w-5/12 float-right md:mb-6 xl:mb-10"> 
      <h4 class="current-start-time">
        End Time:
        <%=@game.end.strftime("%I:%M %p")%>
      </h4>
      <%= form.label :end_time, "Pick new end time", class:"text-gray-600" %><br>
      <%= form.text_field :end_time, class: 'shadow shadow-none w-full h-8 bg-white border-0 border-b border-black timeend-flatpick' %>
    </div>

    <div class="mb-4 md:mb-6 xl:mb-10">
      <%= form.label :location, class:'text-gray-600' %><br>
      <%= form.text_field :location, value: @game.venue, class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
    </div>

    <div class="mb-4 md:mb-6 xl:mb-10">
      <%= form.label :players_required,  class: 'text-gray-600' %><br>
      <%= form.number_field :players_required, class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
    </div>

    <div class="mb-4 md:mb-6 xl:mb-10">
      <%= form.label :cost, class: 'text-gray-600' %><br>
      <%= form.text_field :cost, class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
    </div>
    <div class="mb-4 md:mb-6 xl:mb-10">
      <%= form.label :special_requirements,class: 'text-gray-600' %><br>
      <%= form.text_area :special_requirements,  class: "shadow shadow-none w-full h-24 bg-white border-b border-black" %>
    </div>
    <p>
      <%= form.hidden_field :host_id, value: current_user.id %>
    </p>
    <p>
      <%= form.submit 'Submit', class: "w-full bg-black hover:bg-gray-800 text-white py-2" %>
    </p>
    <% end %>
  </section>

</div>

<%= javascript_pack_tag 'game' %>

app/views/games/new.html.erb
<div class="wrapper">
		<div class="section">
				<%= form_with scope: :game, url: create_game_path, local: true, class: "container flex flex-col justify-around mx-auto w-full md:w-4/5 lg:w-3/5 pb-16 font-body" do |form|%>
				<div class="text-lg font-bold mb-4">
						<h2 class="text-center font-heading text-2xl">Build your team, hassle-free</h2>
				</div>
				<% categories_array = @categories.all.map { |category| [category.game_type, category.id] } %>
				<%= select(:game, :category_id, options_for_select(categories_array), {}, {class: "shadow shadow-none w-full h-8 my-3 mx-auto bg-white border-0 border-b border-black mb-8 text-xl text-gray-600 md:mb-6 text-center xl:mb-10"})%>
				<div class="block mb-4  md:mb-6 xl:mb-10">
						<%= form.label :title, class: 'text-gray-600' %><br>
						<%= form.text_field :title, value: @game_params["title"], class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
						<p class="text-sm text-orange-500">
								<%= show_errors(@game, :title) %>
						</p>
				</div>
				<div class="mb-4 md:mb-6 xl:mb-10">
						<%= form.label :date, class: 'text-gray-600' %><br>
						<%= form.text_field :date, value: @game_params["date"], class: "shadow shadow-none w-full date-flatpick h-8 bg-white border-0 border-b border-black"%>
						<p class="text-sm text-orange-500">
								<%= show_errors(@game, :start) %>
						</p>
						<p class="text-sm text-orange-500">
								<%= show_errors(@game, :end) %>
						</p>
				</div>
				<div class="start-end-time__container flex justify-between items-center">
						<div class="inline-block mb-4 w-5/12 md:mb-6 xl:mb-10">
								<%= form.label :start_time, class: 'text-gray-600' %><br>
								<%= form.text_field :start_time, value: @game_params["start_time"], class: 'shadow shadow-none w-full h-8 bg-white border-0 border-b border-black timestart-flatpick' %>
								<p class="text-sm text-orange-500">
										<%= show_errors(@game, :start) %>
								</p>
						</div>
						<div class="inline-block mb-4 w-5/12 float-right md:mb-6 xl:mb-10">
								<%= form.label :end_time, class: 'text-gray-600' %><br>
								<%= form.text_field :end_time, value: @game_params["end_time"], class: 'shadow shadow-none w-full h-8 bg-white border-0 border-b border-black timeend-flatpick' %>
								<p class="text-sm text-orange-500">
										<%= show_errors(@game, :end) %>
								</p>
						</div>
				</div>
				<div class="mb-4 md:mb-6 xl:mb-10">
						<%= form.label :location, class: 'text-gray-600' %><br>
						<%= form.text_field :location, value: @game_params["location"], class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
						<p class="text-sm text-orange-500">
								<%= show_errors(@game, :venue) %>
						</p>
				</div>
				<div class="mb-4 md:mb-6 xl:mb-10">
						<%= form.label :players_required, class: 'text-gray-600' %>
						<%= form.number_field :players_required,  value: @game_params["players_required"], class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
						<p class="text-sm text-orange-500">
								<%= show_errors(@game, :players_required) %>
						</p>
				</div>
				<div class="mb-4 md:mb-6 xl:mb-10">
						<%= form.label :cost, class: 'text-gray-600' %><br>
						<%= form.text_field :cost, value: @game_params["cost"], class: "shadow shadow-none w-full h-8 bg-white border-0 border-b border-black" %>
				</div>
				<div class="mb-4 md:mb-6 xl:mb-10 w-full text-center">
						<%= form.label :special_requirements, class: 'text-gray-600 text-center w-full mb-4 uppercase tracking-wider' %><br><br>
						<%= form.text_area :special_requirements, value: @game_params["special_requirements"], class: "shadow shadow-none w-full h-24 bg-white border-b border-black p-1" %>
				</div>
				<div>
						<%= form.hidden_field :host_id, value: current_user.id %>
				</div>
				<div>
						<%= form.submit 'Host Game', class: "w-full bg-black hover:bg-gray-800 text-white py-2" %>
				</div>
				<% end %>
		</div>
</div>
<% content_for :js_scripts do %>
<%= javascript_pack_tag 'game', 'data-turbolinks-track': 'reload', defer: true%>
<% end %>

app/views/games/show.html.erb
<% if @game.host_id != current_user.id && (!@rejected_request && !@pending_request && !@accepted_request) && @game_open%>
<div class="game__container flex flex-col justify-around items-center p-2 font-body">
		<h4 class="game-title__header text-2xl uppercase tracking-widest mb-2 p- text-center w-full font-bold font-heading">
				<%=@game.title%>
		</h4>
		<div class="game-what__container flex flex-col justify-around items-center w-3/5 p-3 border-b ">
				<%=image_tag("category_images/" +
		                @game.category.game_type.parameterize(separator: '_') +
		                '.png', class: "max-w-xs object-contain")%>
				<h4 class="game-category__header mb-2 text-xl mb-4">
						<%=@game.category.game_type%>
				</h4>
				<h4 class="game-players__header mb-2">
						<span class="game-players__number <%=" text-orange-500" if @spare_participants %>
								<%="text-gray-500" if !@spare_participants%>">
								<%="#{@game_participants} / #{@game.players_required} "%></span>Participants
				</h4>
				<h4 class="game-cost__header mb-2">Cost:
						<%=@game.cost.to_s.capitalize%>
				</h4>
				<div class="requirements__container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200">
						<h4 class="game-requirements__header mb-2 text-center font-bold">Requirements
						</h4>
						<div class="game-requirements__content w-full text-sm text-center">
								<%=@game.special_requirements%>
						</div>
				</div>
		</div>
		<div class="game-where__container flex flex-col justify-around items-center p-3 border-b w-3/5">
				<h4 class="game-where__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHERE?
				</h4>
				<h4 class="game-venue__header mb-2">
						<%=@game.venue%>
				</h4>
		</div>
		<div class="game-where__container flex flex-col justify-around items-center w-3/5 p-3 border-b">
				<h4 class="game-when__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHEN? </h4>
				<h4 class="game-date__header mb-1">Date:
						<%=@game.start.strftime("%d %b %y") if @game.start%>
				</h4>
				<h4 class="game-start__header mb-1">Starts at:
						<%=@game.start.strftime("%H:%M%P") if @game.start %>
				</h4>
				<h4 class="game-end__header mb-2">Ends:
						<%=@game.end.strftime("%H:%M%P") if @game.end %>
				</h4>
		</div>
		<div class="game-who__container flex flex-col justify-around w-3/5 p-3">
				<h4 class="game-who__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHO? </h4>
				<div class="participants__container flex flex-col justify-around items-center">
						<div class="participants__host-container flex flex-col p-2 justify-around items-center mb-2">
								<h3 class="host__participants-header text-md font-bold">Host</h3>
								<h4 class="game-host py-1 pb-4">
										<%=User.find(@game.host_id).email%>
								</h4>
						</div>
						<%if @game.users.any?%>
						<div class="participants__participants-container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200 mb-2">
								<h3 class="request-accepted__participants-header text-md font-bold ">Participants</h3>
								<%@game.users.each do |user|%>
								<h4 class="game-user-email py-1">
										<%=user.email%>
								</h4>
								<%end%>
						</div>
						<%end%>
				</div>
		</div>
</div>
<%= render 'requests/form', request: Request.new, game: @game %>
<%elsif@game.host_id == current_user.id %>
<div class="game__container flex flex-col justify-around items-center p-2 font-body">
		<h4 class="game-title__header text-2xl uppercase tracking-widest mb-2 p- text-center w-full font-bold font-heading">
				<%=@game.title%>
		</h4>
		<div class="host-requests__container flex flex-col justify-around items-center w-3/5 border-t-2 border-b-2 border-yellow-400 py-6">
				<h3 class="game__header text-center w-full text-gray-700 text-sm p-2 italic font-body">Hey
						<%=current_user.name.downcase.capitalize%>, you are the Host!</h3>
				<% if @host_requests.any?%>
				<h3 class="host-requests__header font-heading mb-2 mt-4 font-bold">Pending Requests</h3>
				<%end%>
				<% @host_requests.each do |request| %>
				<div class="request__container mb-2">
						<h4 class="request-user__header text-center pb-2">
								<%= request.user.email %>
						</h4>
						<%= render 'requests/host_request', request: request, game: @game %>
				</div>
				<%end%>
		</div>
		<div class="game-what__container flex flex-col justify-around items-center w-3/5 p-3 border-b font-body">
				<%=image_tag("category_images/" +
                @game.category.game_type.parameterize(separator: '_') +
                '.png', class: "max-w-xs object-contain")%>
				<h4 class="game-category__header mb-2 text-xl mb-4 font-heading">
						<%=@game.category.game_type%>
				</h4>
				<h4 class="game-players__header mb-2 font-body">
						<span class="game-players__number <%=" text-orange-500" if @spare_participants %>
								<%="text-gray-500" if !@spare_participants%>">
								<%="#{@game_participants} / #{@game.players_required} "%></span>Participants
				</h4>
				<h4 class="game-cost__header mb-2">Cost:
						<%=@game.cost.to_s.capitalize%>
				</h4>
				<div class="requirements__container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200">
						<h4 class="game-requirements__header mb-2 text-center font-bold">Requirements
						</h4>
						<div class="game-requirements__content w-full text-sm text-center">
								<%=@game.special_requirements.capitalize%>
						</div>
				</div>
		</div>
		<div class="game-where__container flex flex-col justify-around items-center p-3 border-b w-3/5">
				<h4 class="game-where__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHERE?
				</h4>
				<h4 class="game-venue__header mb-2">
						<%=@game.venue%>
				</h4>
		</div>
		<div class="game-when__container flex flex-col justify-around items-center w-3/5 p-3 border-b">
				<h4 class="game-when__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHEN? </h4>
				<h4 class="game-date__header mb-1">Date:
						<%=@game.start.strftime("%d %b %y") if @game.start%>
				</h4>
				<h4 class="game-start__header mb-1">Starts at:
						<%=@game.start.strftime("%H:%M%P") if @game.start %>
				</h4>
				<h4 class="game-end__header mb-2">Ends:
						<%=@game.end.strftime("%H:%M%P") if @game.end %>
				</h4>
		</div>
		<div class="game-who__container flex flex-col justify-around w-3/5 p-3">
				<h4 class="game-who__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHO? </h4>
				<%if @game.users.any?%>
				<div class="participants__container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200 mb-2">
						<h3 class="request-accepted__participants-header text-md font-bold mb-1">Participants</h3>
						<%@game.users.each do |user|%>
						<h4 class="game-user-email">
								<%=user.email%>
						</h4>
						<div class="kick-user__link flex justify-center items-center w-full pt-1">
								<%= link_to "Kick #{user.name.downcase.capitalize}", remove_games_users_path(:user_id => user.id), id: @game.id, method: :delete, data: { confirm: 'Are you sure?' }%>
						</div>
						<%end%>
				</div>
				<%end%>
		</div>
		<div class="game-edit-delete__links-container flex justify-around w-2/4 py-4">
				<%=link_to "Edit", {controller: "games", action: "edit"}, id: @game.id, class: "btn btn-default mr-6 bg-white text-black border-b border-orange-400 uppercase tracking-wider" %>
				<%= link_to 'Delete', @game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default ml-6 bg-white text-black border-b border-orange-400 uppercase tracking-wider" %>
		</div>
</div>
<%elsif @rejected_request || @pending_request || @accepted_request || !@game_open%>
<div class="game__container flex flex-col justify-around items-center p-2 font-body">
		<h4 class="game-title__header text-2xl uppercase tracking-widest mb-2 p- text-center w-full font-bold font-heading">
				<%=@game.title%>
		</h4>
		<div class="host-requests__container flex flex-col justify-around items-center w-3/5 border-t-2 border-b-2 border-yellow-400 py-6">
				<h3 class="game__header text-center w-full text-gray-700 text-sm p-2 italic font-body ">Hey
						<%=current_user.name.to_s.downcase.capitalize%>
				</h3>
				<%if !@game_open && !@accepted_request && !@rejected_request && !@pending_request%>
				<h3 class="request-rejected__header text-center w-full text-gray-700 text-sm p-2 italic font-body">This Game is full at the moment :(</h3>
				<%elsif @rejected_request%>
				<h3 class="request-rejected__header text-center w-full text-gray-700 text-sm p-2 italic font-body">You have been rejected by the Host :(</h3>
				<%elsif @pending_request%>
				<h3 class="request-pending__header text-center w-full text-gray-700 text-sm p-2 italic font-body">Your request is pending</h3>
				<div class="withdraw-request__container flex flex-col justify-center items-center w-full mt-2">
						<%= link_to 'Withdraw Request', destroy_request_path(@pending_request), method: :delete, data: { confirm: 'Are you sure?' }%>
				</div>
				<%elsif @accepted_request%>
				<h3 class="request-accepted__header text-center w-full text-gray-700 text-sm p-2 italic font-body">Your request has been accepted by the Host!</h3>
				<div class="leave-game__container flex flex-col justify-center items-center w-full mt-2">
						<%= link_to 'Leave Game', remove_games_users_path(:user_id => current_user.id), id: @game.id, method: :delete, data: { confirm: 'Are you sure?'}, class: "mt-4"%>
				</div>
				<%end%>
		</div>
		<div class="game-what__container flex flex-col justify-around items-center w-3/5 p-3 border-b ">
				<%=image_tag("category_images/" +
		                @game.category.game_type.parameterize(separator: '_') +
		                '.png', class: "max-w-xs object-contain")%>
				<h4 class="game-category__header mb-2 text-xl mb-4 font-heading">
						<%=@game.category.game_type%>
				</h4>
				<h4 class="game-players__header mb-2">
						<span class="game-players__number <%=" text-orange-500" if @spare_participants %>
								<%="text-gray-500" if !@spare_participants%>">
								<%="#{@game_participants} / #{@game.players_required} "%></span>Participants
				</h4>
				<h4 class="game-cost__header mb-2">Cost:
						<%=@game.cost.to_s.capitalize%>
				</h4>
				<div class="requirements__container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200">
						<h4 class="game-requirements__header mb-2 text-center font-bold">Requirements
						</h4>
						<div class="game-requirements__content w-full text-sm text-center">
								<%=@game.special_requirements.capitalize%>
						</div>
				</div>
		</div>
		<div class="game-where__container flex flex-col justify-around items-center p-3 border-b w-3/5">
				<h4 class="game-where__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHERE?
				</h4>
				<h4 class="game-venue__header mb-2">
						<%=@game.venue%>
				</h4>
		</div>
		<div class="game-where__container flex flex-col justify-around items-center w-3/5 p-3 border-b">
				<h4 class="game-when__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHEN? </h4>
				<h4 class="game-date__header mb-1">Date:
						<%=@game.start.strftime("%d %b %y") if @game.start%>
				</h4>
				<h4 class="game-start__header mb-1">Starts at:
						<%=@game.start.strftime("%H:%M%P") if @game.start %>
				</h4>
				<h4 class="game-end__header mb-2">Ends:
						<%=@game.end.strftime("%H:%M%P") if @game.end %>
				</h4>
		</div>
		<div class="game-who__container flex flex-col justify-around w-3/5 p-3">
				<h4 class="game-who__header w-full text-center text-lg text-orange-600 tracking-wider mb-2 font-heading">
						WHO? </h4>
				<div class="participants__container flex flex-col justify-around items-center">
						<div class="participants__host-container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200 mb-2">
								<h3 class="host__participants-header text-md font-bold">Host</h3>
								<h4 class="game-host py-1 pb-4">
										<%=User.find(@game.host_id).email%>
								</h4>
						</div>
						<%if @game.users.any?%>
						<div class="participants__participants-container p-4 w-full flex flex-col justify-around items-center border-2 border-gray-200 mb-2">
								<h3 class="request-accepted__participants-header text-md font-bold ">Participants</h3>
								<%@game.users.each do |user|%>
								<h4 class="game-user-email py-1">
										<%=user.email%>
								</h4>
								<%end%>
						</div>
						<%end%>
				</div>
		</div>
</div>
<%end%>
<%# Render link to Chat Room if current_user is participant/host%>
<% if @user_in_game || current_user.id == @game.host_id%>
<div class="chat-room-link__container w-full flex justify-center mb-4 text-xl pb-4">
		<!-- 		<%=link_to "Chat Room", controller: "rooms", action: "show", id: @room.id, class: "chat-room__link"%> -->
		<%=link_to controller: "rooms", action: "show", id: @room.id, class: "chat-room__link" do%>
		<%= image_tag("icons8-chat-100.png") %>
		<% end %>
</div>
<%end%>