config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  root to: 'home#index'

  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "signup" }

  # landing page
  get 'featured_games', to: 'home#featured_games';

  get 'categories', to: 'categories#index', as: 'categories'
  get 'categories/sort', to: 'categories#sort'

  get 'games/new', to: 'games#new', as: 'new_game'
  get 'games/:id', to: 'games#show', as: 'game'
  get 'games/:id/edit', to: 'games#edit', as: 'edit_game'
  post 'games/new', to: 'games#create', as: 'create_game'
  put 'games/:id', to: 'games#update'
  delete 'games/:id', to: 'games#destroy'
  delete 'games/:id/user/:user_id', to: 'games#remove_games_users', as: 'remove_games_users'

  get 'users/:id', to: 'users#show_profile'
  get 'users/:id/edit', to: 'users#edit'
  put 'profile', to: 'users#update', as: 'update_profile'
  get 'dashboard', to: 'users#show_dashboard', as: 'dashboard'
  get 'profile', to: 'users#show_profile', as: 'profile'

  get 'rooms/:id', to: 'rooms#show'

  post 'messages', to: 'messages#create'

  post 'requests', to: 'requests#create'
  put 'requests', to: 'requests#update', as: 'edit_request'
  delete 'requests/:id', to: 'requests#destroy', as: 'destroy_request'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :game
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  require 'json'

  def index
    # @games = Game.all
    @user_id = current_user[:id]

    if params.has_key?(:category_id)
      @category_id = params[:category_id].to_i
      @games = Game.where(category_id: @category_id).where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)
    else
      @games = Game.where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)
    end

    @categories = Category.all
    #Edit links here for navbar
    @links = [{:name => "Home", :path => root_path},{:name => "Host a Game", :path => new_game_path}, {:name => "Dashboard", :path => dashboard_path}]
  end

  def sort
    @categories = Category.all
    @user_id = current_user[:id]

    if params[:title] != ""
      @title = params[:title]
      @games = Game.where("title like ?", "%#{@title}%").where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)

    elsif params[:date] == "" and params[:category_id] == ""
      @games = Game.where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)

    elsif params[:date] == ""
      @category_id = params[:category_id].to_i
      @games = Game.where(category_id: @category_id).where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)

    elsif params[:category_id] == ""
      date = Date.parse(params[:date])
      @games = Game.where(start: date.midnight..date.end_of_day).where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)

    else
      @category_id = params[:category_id].to_i
      date = Date.parse(params[:date])
      @games = Game.where(category_id: @category_id, start: date.midnight..date.end_of_day).where.not(host_id: @user_id).paginate(page: params[:page], per_page: 4)
    end

  end

  def show
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_card.html.erb
<%
	def get_category(category_id)
		for category in @categories
			if category.id == category_id
				return category.game_type
			end
		end
	end
%>
<%= will_paginate @games, class: "mb-2 text-xl md:text-lg" %>
<% @games.each do |game| %>
<!-- card will adjust to fit the dimension of its container -->
<div class="card gallery-item gallery-item_short gallery-item_wide gallery-item_left_aligned p-1">
		<%if User.find(game.host_id)%>
		<% if User.find(game.host_id).avatar.attached?%>
		<%= image_tag main_app.url_for(User.find(game.host_id).avatar), class: "card-img object-cover js-menu-toggle navbar-item" %>
		<%else%>
		<%= image_tag User.find(game.host_id).gravatar_url, class: "card-img object-cover js-menu-toggle navbar-item" if User.find(game.host_id)%>
		<%end%>
		<%end%>
		<h1 class="card-title">
				<%=get_category(game.category_id)%>
		</h1>
		<h2 class="card-subtitle">
				<%=game.title%>
		</h2>
		<div class="card-body">
				<p>
						<i class="fas fa-calendar text-black icon"></i>
						<%=game.start.strftime("%d %b") if game.start%>
				</p>
				<p>
						<i class="fas fa-clock text-black icon"></i>
						Start time:
						<%=game.start.strftime("%H:%M") if game.start%>
				</p>
				<p> <i class="fas fa-clock text-black icon"></i> End time:
						<%=game.end.strftime("%H:%M") if game.end%>
				</p>
				<p>
						<i class="fas fa-compass text-black icon"></i>
						<%=game.venue%>
				</p>
		</div>
		<div class="card-footer flex justify-between">
				<p> Players required:
						<%=game.players_required%>
				</p>
				<%= link_to "Details", game_path(game.id),  class:'btn btn-default btn-sm' %>
				<%
=begin%>
				<%= link_to "Details", controller: "games", action: "show", id: game.id, class: "btn btn-default btn-sm" %>
				<%
=end%>
		</div>
</div>
<% end %>
<%= will_paginate @games, class: "text-xl md:text-lg" %>

app/views/categories/index.html.erb
<!-- Search bar. Confirm whether search is for any field or for a specific field -->
<div class="wrapper">
		<div class="section flex flex-col justify-between items-center text-center font-body pb-8 border-b">
				<p class="font-semibold py-4 font-heading text-2xl">Search for a Game!</p>
				<%= form_with url: categories_sort_url, method: "get", class: "flex flex-col justify-around items-center w-11/12 py-2" do |form| %>
				<div class="categories__fields-container flex flex-col sm:flex-row justify-around items-center w-full">
						<%= form.text_field :title, placeholder: "Title", class: 'w-full h-10 bg-white autocomplete mr-2 px-2' %><br>
						<%= form.text_field :date, placeholder: "Date", class: 'w-full h-10 bg-white sortdate-flatpick mr-2 px-2' %><br>
						<% categories_array = @categories.all.map { |category| [category.game_type, category.id] } %>
						<%= form.select(:category_id, options_for_select(categories_array), {:include_blank => "-Select Category-"}, {class: "w-full h-10 bg-white mr-2 px-2"})%><br>
				</div>
				<%= form.submit 'Find Game', class: "btn-default btn px-4 mx-2 sm:mt-6" %>
				<% end %>
		</div>
		<div class="section sm:flex sm:justify-center">
				<div class="game-cards-container">
						<%= render 'categories/card' %>
				</div>
		</div>
</div>
<% content_for :js_scripts do %>
<%= javascript_pack_tag 'category', 'data-turbolinks-eval': true,'data-turbolinks-track': 'reload'%>
<%end %>

app/views/categories/sort.js.erb
document.querySelector('.game-cards-container').innerHTML = "<%= escape_javascript(render 'categories/card') %>"